INSERT INTO GAMES(NAME, PROVIDER_ID) VALUES('Counter-Strike: Global Offensive', 1372,),
INSERT INTO GAMES(NAME, PROVIDER_ID) VALUES('Dota 2', 2963);
INSERT INTO GAMES(NAME, PROVIDER_ID) VALUES('Apex Legends', 114795);
INSERT INTO GAMES(NAME, PROVIDER_ID) VALUES('Call of Duty: Warzone', 131800);